branch: release

#Things a wanna execute
tasks:
  - test:
      cmd: mvn test
  - compile:
      cmd: mvn compile
  - clean:
      cmd: mvn clean
  - checkout:
      cmd: echo "Checking out the code"
  - fail:
      cmd: exit 1
  - write_file:
      cmd: touch /tmp/failfast.txt


# Ordenaded way to run my steps
pipelines:
  - checkout:
    - checkout
  - test:
     - test
  - release:
      - build
      - integration
      - compress
  - compile:
     - clean
     - compile
  - failfast:
     - fail
     - write_file
